name: core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install_geotiff
      run: |
        wget https://github.com/kmader/spark-imageio/releases/download/just_geo/geotiff-jai.jar
        mvn install:install-file -Dfile=geotiff-jai.jar -DgroupId=geotiff -DartifactId=geotiff-jai -Dversion=0.0 -Dpackaging=jar -DlocalRepositoryPath=
    - name: Build Core
      run: |
        cd core
        mvn install -DskipTests -Dcheckstyle.skip
        cd ..;
    - name: Build Scifio
      run: |
        cd spark-scifio
        mvn install -DskipTests -Dcheckstyle.skip
        cd ..;
    - name: Build IJ
      run: |
        cd spark-ij
        mvn install -DskipTests -Dcheckstyle.skip
        cd ..;
    - name: Build ImageIO
      run: |
        cd spark-imageio
        mvn install -DskipTests -Dcheckstyle.skip
        cd ..;
